apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: v1.7.2
    helm:
      values: |
        persistence:
          defaultClassReplicaCount: 2
        defaultSettings:
          defaultReplicaCount: 2
          replicaSoftAntiAffinity: true
          storageOverProvisioningPercentage: 200
        preUpgradeJob:
          enabled: false
  destination:
    name: workloads-cluster  # The name you gave it in the CLI
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
