apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-workloads
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.13.3
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    name: workloads-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
