apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: v1.7.2
    helm:
      values: |
        ingress:
          enabled: true
          host: longhorn.workloads.example.com
          annotations:
            cert-manager.io/cluster-issuer: "internal-ca-issuer"
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
          tls: true
          tlsSecret: longhorn-ui-tls
        persistence:
          defaultClassReplicaCount: 2
        defaultSettings:
          defaultReplicaCount: 2
          replicaSoftAntiAffinity: true
          storageOverProvisioningPercentage: 200
        preUpgradeChecker:
          jobEnabled: false
        preUpgradeJob:
          enabled: false
  destination:
    name: workloads-cluster
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true