apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-{{ .Values.tenantName }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vayvanna/idp-ish-2-infra
    targetRevision: HEAD
    path: current-state/kubernetes/workloads/tenants/{{ .Values.tenantName }}/manifests-used/kubevela-app.yaml
  destination:
    name: workloads-cluster # IMPORTANT: Root app stays on Management!
    namespace: {{ .Values.tenantName }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
